version: "3"

services:
  detect:
    image: detect:init
    volumes:
      - volume:/mnt
    networks:
      - bridge
    command: python3 main.py

  pose:
    image: pose:init
    volumes:
      - volume:/mnt
    networks:
      - bridge
    command: python3 main.py

  segmentation:
    image: segmentation:init
    volumes:
      - volume:/mnt
    networks:
      - bridge
    command: python3 main.py

  clustering:
    image: clustering:init
    volumes:
      - volume:/mnt
    networks:
      - bridge
    command: python3 main.py

  server:
    image: server:init
    volumes:
      - volume:/mnt
    networks:
      - bridge
    ports:
      - "17780:8000"
    command: python3 main.py

volumes:
  {}

networks:
  bridge: {}