version: "3"

services:
  detect:
    build: ./detect
    image: detect:init
    networks:
      - bridge
    command: python3 main.py

  pose:
    build: ./pose
    image: pose:init
    networks:
      - bridge
    command: python3 main.py

  segmentation:
    build: ./segmentation
    image: segmentation:init
    networks:
      - bridge
    command: python3 main.py

  clustering:
    image: clustering:init
    networks:
      - bridge
    command: python3 main.py

  server:
    build: ./server
    image: server:init
    networks:
      - bridge
    ports:
      - "17780:8000"
    command: python3 main.py

networks:
  bridge:
    driver: bridge
